# Generated by Django 4.1.4 on 2022-12-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
    ]
