# Generated by Django 4.1.4 on 2022-12-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0006_project_learning_project_programming_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
