# Generated by Django 4.1.4 on 2022-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0007_alter_project_options_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deploy',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
