# Generated by Django 4.1.4 on 2022-12-20 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0008_alter_project_options_project_cover_project_deploy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
    ]
