# Generated by Django 4.1.4 on 2022-12-21 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0009_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
    ]
