# Generated by Django 4.1.4 on 2022-12-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0010_project_slug_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
