# Generated by Django 4.1.4 on 2022-12-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0012_remove_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teste',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
