# Generated by Django 4.1.4 on 2022-12-21 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0013_project_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
