# Generated by Django 4.1.4 on 2022-12-21 04:25

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0021_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, max_length=100, null=True, populate_from='title', unique=True),
        ),
    ]
