# Generated by Django 4.1.4 on 2022-12-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0022_alter_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='programming_languages',
            new_name='tags',
        ),
    ]
