# Generated by Django 4.1.4 on 2022-12-22 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0023_rename_programming_languages_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
    ]
