# Generated by Django 4.1.4 on 2022-12-23 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0024_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 23)),
        ),
    ]
