# Generated by Django 4.1.4 on 2022-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0027_visitorspost_project_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorspost',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Comente sobre os projetos:'),
        ),
    ]
