# Generated by Django 4.1.4 on 2022-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0028_alter_visitorspost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorspost',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Deixe um comentário'),
        ),
    ]
