# Generated by Django 4.1.4 on 2022-12-27 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0029_alter_visitorspost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorspost',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='visitorspost',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 12, 26)),
        ),
    ]
