# Generated by Django 4.1.4 on 2022-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0030_alter_visitorspost_options_visitorspost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorspost',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
