# Generated by Django 4.1.4 on 2023-01-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0032_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorspost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
