# Generated by Django 4.1.4 on 2023-01-13 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0033_alter_visitorspost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 1, 13)),
        ),
    ]
